config/routes.rb
Rails.application.routes.draw do
  root to: 'reviews#index'
  resources :reviews 

  resources :reviews do
    resources :comments
  end

  resources :reviews do
    resources :ratings
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :presence => true
  belongs_to :review
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :review
  validates :score, :presence => true

end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :title, :presence => true
  validates :content, :presence => true
  has_many :comments
  has_many :ratings

  def self.search(query)
    where("genre = ?", "#{query}")
  end

  def average_rating
    sum = 0
    score_length = self.ratings.length
    self.ratings.each do |rating|
      sum += rating.score
    end
    if score_length != 0
      return (sum/score_length).to_f
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @review = Review.find(params[:review_id])
    @comment = @review.comments.new
  end

  def create
    @review = Review.find(params[:review_id])
    @comment = @review.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "Comment successfully added!"
      redirect_to review_path(@review)
    else
      render :new
    end
  end

  def destroy
    review = Review.find(params[:review_id])
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to review_path(review)
  end

private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def new
    @review = Review.find(params[:review_id])
    @rating = @review.ratings.new
  end

  def create
    @review = Review.find(params[:review_id])
    @rating = @review.ratings.new(rating_params)
    if @rating.save
      flash[:notice] = "Rating successfully added!"
      redirect_to review_path(@review)
    else
      render :new
    end
  end

private
  def rating_params
    params.require(:rating).permit(:score)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index

    if params[:genre]
      @reviews = Review.search(params[:genre])
      @feature = Review.all.sample
    else
      @reviews = Review.order(params[:sort])
      @feature = @reviews.sample
    end
  end

  def show
    @review = Review.find(params[:id])
    @comments = @review.comments
    @ratings = @review.ratings
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)

    if @review.save
      flash[:notice] = "Review successfully added!"
      redirect_to reviews_path
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    # binding.pry
    if @review.update(review_params)
      redirect_to review_path(@review)
    else
      render :edit
    end
  end

private
  def review_params
    params.require(:review).permit(:title, :content, :user_id, :genre)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @reviews = Review.order(params[:sort])
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for [@review, @comment] do |f| %>
  <div class="form-group">
    <strong><%= f.label :content %></strong>
    <%= f.text_area :content, rows: '10', class: "form-control" %>
  </div>
    <%= f.submit %>
<% end %>

app/views/comments/new.html.erb
<h1>Add Comment</h1>

<%= render 'form' %>
<br>
<%= link_to "Back to Review", review_path(@review) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Music Reviews</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home<span class="sr-only">(current)</span></a></li>
        <li><a href="#"><%= yield(:navbar) %></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>







<div class="container">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
</div>


</body>
</html>

app/views/ratings/_form.html.erb
<%= form_for [@review, @rating] do |f| %>
  <%= f.label :score %>
  <%= f.number_field :score %>
  <%= f.submit %>
<% end %>

app/views/ratings/new.html.erb
<h1>Add Rating</h1>

<%= render 'form' %>

app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :genre %>
  <%= f.select(:genre, options_for_select(["hip-hop/rap", "rock", "classical", "electronic", "alternative", "indie", "pop"])) %>
  <%= f.label :content %>
  <%= f.text_area :content, rows: '10' %>
  <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<% content_for(:title, "Edit Review") %>
<%= render 'form' %>
<br>

app/views/reviews/index.html.erb
<% content_for(:title, "Music | Reviews") %>
<% content_for(:random, @feature.title) %>
<center><legend>
  <h1>Music Reviews</h1>
  <%= link_to 'Sort By Alphabetical', :sort => "lower(title)" %> ||
  <%= link_to 'Sort By Date Added', :sort => "(created_at)" %>
  <br><br>
</legend></center>
<center><% for review in @reviews %>
  <h3><%= link_to review.title, review_path(review) %></h3>
  <br>
<% end %></center>
<hr>
<center><%= form_tag(reviews_path, :method => 'get', id: 'search-form') do %>
  <%= select_tag(:genre, options_for_select(["Select Genre", "hip-hop/rap", "rock", "classical", "electronic", "alternative", "indie", "pop"]), selected: :genre) %>
  <button type="submit">Filter Review by Genre!</button>
  <% end %>
  <%= link_to "All genres", reviews_path %></center>



<h1>Featured Review</h1>
<h3><%= link_to @feature.title, review_path(@feature) %></h3>
<hr>
<h3>Submit a Review</h3>
<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<% content_for(:title, "Add Review") %>
<% content_for(:random, "with more time this would be a useful link")  %>
<h1>Add Review</h1>

<%= render 'form' %>

app/views/reviews/show.html.erb
<% content_for(:title, @review.title) %>


<legend><h1><%= @review.title %></h1></legend>

<p>
  <div class="review-content">
    <%= @review.content %>
  </div>
  <h4>Genre</h4>
  <%= @review.genre %>
  <hr>
  <strong><p>This Review's Average Rating:</p></strong>
  <%= @review.average_rating %>
</p>
<br>
<h3>Comments:</h3>
<% @comments.each do |comment| %>
  <%= comment.content %>
  <%= link_to 'Delete Comment', review_comment_path(@review, comment),
                                :data => {:confirm => "you sure?"},
                                :method => "delete" %>
  <br>
<% end %>
<br><br>
<%= link_to 'Add comment', new_review_comment_path(@review) %><br>
<%= link_to 'Add Rating', new_review_rating_path(@review) %><br>
<%= link_to 'Delete Review', review_path(@review),
                              :data => {:confirm => "you sure?"},
                              :method => "delete" %><br>
<%= link_to 'Edit Review', edit_review_path(@review) %><br><br>
<%= link_to 'All Reviews', reviews_path %>